server:
  port: 8082

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sbbb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: sbsst
    password: sbs123414
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace

cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    s3:
      bucket: instakg-team
      dir: /
    region:
      static: ap-northeast-2
    stack:
      auto: false

